name: "tests-nix-macos"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
          nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: eigenvalue
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: "./run_tests.sh --no-cargo-build"
